### ISSUE TITLE
[Request] Hit points recovered from hit dice fraction

### ISSUE THREAD

**Issue by SLinxTheFox** [roth-michael/FoundryVTT-RestRecovery#163]
The rest recovery i use halves hit dice rolls, but i don't see that option. this option would make this module's health recovery sextion useable for me and I would appreciate it so much

**Comment by Haxxer** [comment]
I will not be implementing this, but this module is open source and accepts code contributions from anyone :)

**Comment by SLinxTheFox** [comment]
oh butts, uhhm. I know a liiitle bit of code and can usually do simple things with some guidance from others. Would adding that be fairly simple?
