### ISSUE TITLE
[Request] Remember Players

### ISSUE THREAD

**Issue by TheAlexPlus** [roth-michael/FoundryVTT-RestRecovery#166]
**Is your feature request related to a problem? Please describe.**
I can't tell if this is an error I'm running into or if it's just the way it is, but Rest Recovery never remembers the actors ive chosen for resting.

**Describe the solution you'd like**
I wish it would remember

**Describe alternatives you've considered**
I wish I could set which owned actors should be auto populated

**Additional context**
MY players have multiple summons and I stream our games, so their tokens are also observers for another player account..  when i go into the menu, it's tons of options long.  It would be easier to redo every time if it didn't list everything with a player associated to it or if i could filter it somehow.

Although I feel like in the past it has remembered before and its not clear exactly what changed on my end.

**Comment by roth-michael** [comment]
Hi - is this still happening for you? I don't think I've encountered it. If so, what version of foundry & dnd5e core are you running?
