### ISSUE TITLE
[Request] Custom Rest Times

### ISSUE THREAD

**Issue by Witchcrafter1** [roth-michael/FoundryVTT-RestRecovery#183]
**Is your feature request related to a problem? Please describe.**
I would like an option to set custom times for rests.
For example that a short rest is only 30 min instead of 1h. Or that the Long Rest goes for 10 hours.

Optional it could also allow for multiple Rest Times. Like the first two short rests are 10 min and after that each short rest is 1 hour.

**Describe the solution you'd like**
This option should integrate with midi and simple calender, so that effects etc expire correctly.

**Describe alternatives you've considered**
Manual adjustment.

**Comment by Haxxer** [comment]
I will not be implementing this, but this module is open source and accepts code contributions from anyone :)
