### ISSUE TITLE
[Request] Limit which actors are resting

### ISSUE THREAD

**Issue by jlafuenti** [roth-michael/FoundryVTT-RestRecovery#188]
**Is your feature request related to a problem? Please describe.**
I am running a campaign with multiple sets of characters (turn of fortunes wheel).  When a short or long rest happens, only a subset of players are actually resting (3 out of 9).  However when they take a rest, the abilities of the nonpresent characters are used.  for example, one of the absent characters is a bard and song of rest will be applied even though the bard isn't present

**Describe the solution you'd like**
Maybe take into account the active map and which player actors are present, or possibly have a dialog asking who is taking part in the rest and only apply those abilities

**Describe alternatives you've considered**
Alternately ask if each ability should be applied, allowing the player to select no or yes depending on which character the ability is coming from

**Comment by roth-michael** [comment]
Currently when you prompt a rest, it should give the option of selecting which characters are resting - if in your example the bard is not selected, none of the players should the benefits of song of rest. Do you not get that dialog with the prompt? What version are you running?

**Comment by jlafuenti** [comment]
No, when doing a short rest or Long rest, I get a confirmation that I want
to perform the rest, and can select to roll hit die (for short rest) but it
is auto applying the song of rest feature. no mention at all of who is
resting or anythinig of the sort
This is foundry v11 build 315, dnd 5e v2.4.1 Module v1.5.4

**Comment by roth-michael** [comment]
I see - I didn't realize you were prompting the rests from the character sheets. As a GM, you should have a "Prompt Rest" button on the lower left of your screen, underneath the list of Players. 
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/72220390/e47f362f-cbcc-4795-957a-2fb7679d1737)

Within that prompt, you can choose which PCs to prompt a rest for, and it will send each of your players (who are online) the appropriate rests as if they've done them directly from their character sheet, but will also take into account your choices as you've asked for above. 
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/72220390/dcbee72d-9a06-4761-be97-0ecfd5d391ac)


So for example even if you have a bard on the active scene, you could choose to only prompt rests for other characters, and nobody would benefit from Song of Rest.

**Comment by jlafuenti** [comment]
Well dang, I just tested and that fixed my issue... I'll just start doing
that for now on and turn off their ability to do it from their character
sheets.
Thanks for the help, somehow never noticed the rest button on my screen.

**Comment by roth-michael** [comment]
It's sneaky hiding down by the corner. Glad it's working for you!
