### ISSUE TITLE
[BUG] Conflict with Unfulfilled Rolls module prevents rolling for HP on short rest

### ISSUE THREAD

**Issue by dineshm72** [roth-michael/FoundryVTT-RestRecovery#190]
**Describe the bug**
With just RR5e and Unfulfilled Rolls (and a couple libraries) enabled, if you take a short rest, clicking the Roll and Autoroll buttons do not do anything.

The following error is displayed in console:
<img width="372" alt="image" src="https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/2231877/5cd12571-c344-468b-b212-0bf1d79cbadb">

Unfulfilled rolls is used to allow for manual rolling or Bluetooth dice (like Pixels or GoDice) rolling.

**To Reproduce**
1. Click on Prompt Rest
2. Click on Short Rest
3. Click to roll for offline players if needed (note: happens even when players are online) 
4. Click to Roll or Auto-Roll for a PC who is missing HP.  

**Expected behavior**
HP should roll

**Screenshots**
Not very elucidating, but here is the dialog:
<img width="343" alt="image" src="https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/2231877/6dfede45-c37d-4da3-83ac-a6588f255bdc">

**Setup:**
 - Foundry Version: 11.315
 - System Version: dnd 2.4.1
 - Rest Recovery Version: 1.5.4
 - Browser & version chrome

**Active modules:**
 - Rest Recovery
 - libwrapper
 - Unfulfilled Rolls
 - socketlib
 - FTC

**Additional context**
Error is being thrown by Unfulfilled Rolls, but not clear to me whether the cause is there or here.  Probably there, but I am filing it here just in case.  Possibly related to this: https://github.com/foundryvtt/unfulfilled-rolls/issues/35

**Comment by dineshm72** [comment]
This is still an issue in dnd 3.1.2 with RR 1.6.1 and UR 0.1.4.

Trying to roll from short rest dialog, with only the above 2 mods plus FTC, libwrapper, and socketlib (and the forge).
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/2231877/e6e9b9fc-4647-459f-8cdb-167f2d3fc160)

I'm guessing it's an issue with UR really, but possibly it can be coded against on the RR side.  For example, trying "/r d20" will cause an UR error, but trying "/r 1d20" pops up the UR dialog fine.  So it might be that some more expressive formatting would work.  But it could also be a limitation in UR that can't be avoided, like the above linked error is I believe.

**Comment by roth-michael** [comment]
Sure enough (as we discussed on discord) this is an issue with unfulfilled rolls. Can't address from here (and come V12 won't be relevant) so closing the issue.
