### ISSUE TITLE
[BUG] Players able to initiate rest while prevent toggled on.

### ISSUE THREAD

**Issue by Oh-My-God-What** [roth-michael/FoundryVTT-RestRecovery#193]
**Describe the bug**
DNDv3.x + . with the new character sheets, players are able to initiate rest themselves even when setting for "Prevent Player Rest" is toggled on.

**Expected behavior**
Players should not be able to initiate rest.

**Setup:**
 - Foundry Version: [e.g. 11 build 315]
 - System Version: [e.g. DND5e 3.0.4]
 - Rest Recovery Version: [e.g. 1.5.4]
 - Browser & version [Chrome]

**Active modules:**
 - Rest Recovery
 - libwrapper

**Comment by roth-michael** [comment]
Not seeing this behavior on DND5e 3.1.2, for what it's worth. Trying gives the appropriate warning but doesn't result in a rest.

**Comment by Oh-My-God-What** [comment]
> Not seeing this behavior on DND5e 3.1.2, for what it's worth. Trying gives the appropriate warning but doesn't result in a rest.

Interesting, i have been debating updating to 3.1.2. I may update my test and try it out.

**Comment by roth-michael** [comment]
If you do, come on back and let me know if it works!

**Comment by Oh-My-God-What** [comment]
> If you do, come on back and let me know if it works!

Sorry for the late response, yes it is working again after updating to 3.1.2. Thank you!
