### ISSUE TITLE
[BUG] Items that delete when empty do not trigger any response from the module

### ISSUE THREAD

**Issue by Commander-Fayne** [roth-michael/FoundryVTT-RestRecovery#201]
If an item is set to Destroy on Empty under Consumable Usage, the module does not give any update or run food/water automation. 

The item is set up properly as a consumable and is a food item. It has "Item is consumable" checked and is set to Water (food has the same problem). It has 1/1 charges, and has Destroy on Empty and Uses Prompt checked. When the player uses the item, the chat shows the item is used, but there is no response from RestRecovery. If it matters, this is using Tidy Sheet.

**To Reproduce**
Create new consumable
Under Details Tab, under Consumable Details, set item to Food with Consumable Type dropdown
Under Rest Recover tile, check "Item is Consumable" and set the Type to Water with the dropdown (food experiences the same issue)
Leave "One charge worth entire day worth"
Under Consumable Usage, set Activation Cost to Action to gain access to the rest of the options
Check "Destroy on Empty" and "Uses Prompt"
Leave Consumable Activation empty

**Expected behavior**
There should be the usual "[Player] drank [Item Name] for 1 units of water. They require [remaining required uses] of water to be sated for the day."

However, all that happens is the chat output shows the Water item was used, but no response from RestRecovery

**Screenshots**
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/97197751/9edb7164-953b-43ef-943a-acd0aa52c946)
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/97197751/ccfe133c-bfec-462b-9e5d-35bb89d88395)

Expected Outcome should be
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/97197751/e06d4d0c-cca8-46fa-9fdb-f587234173c9)
This was obtained by setting an item to not delete on empty, thereby leaving the water item with 0/1 charges remaining and still in inventory

**Setup:**
 - Foundry Version: 11.315
 - System Version: DnD5e 3.1.2
 - Rest Recovery Version: 1.6.3
 - Browser & version Google Chrome 124.0.6367.207

**Active modules:**
Tested with only the following modules active:
 - Rest Recovery
 - libwrapper
 - Midi QOL
 - socketlib

**Comment by Commander-Fayne** [comment]
Update after further testing. If the item is set to destroy on empty and is in a stack of more than 1, the module behaves normally, e.g. if there are 2 Water, you use one and the stack drops to 1, the Rest Recover module reports the player drank 1 water and needs 1 more to feel sated.

**Comment by roth-michael** [comment]
Yup can confirm. I'll see if I can figure out why and have it fixed for the next update. Thanks!

**Comment by roth-michael** [comment]
This'll be fixed in 1.6.4 (hopefully out within the next day).
