### ISSUE TITLE
[BUG] Translations

### ISSUE THREAD

**Issue by Kharmans** [roth-michael/FoundryVTT-RestRecovery#205]
When I translate the module to pt-BR, I notice that the **Prompt Rest** button is not translated, and the options **Player characters to prompt rests for** and **Rest Profile** aren't translated either. I think they are not on the .json language file.

![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/112586547/aaf66bd5-98fe-4b50-8195-d318c75af394)
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/112586547/a30246de-4267-4a3d-ae26-3037198a8ba5)

**Comment by roth-michael** [comment]
Yep that's a bug! I’ll try to address it tomorrow. Could you share your translations for those 3 below, that way I can include them in the pt_BR.json in the same push?

**Comment by Kharmans** [comment]
Of course!

**Prompt Rest**: Solicitar Descanso
**Player characters to prompt rests for**: Personagens de Jogadores para Solicitar Descansos
**Rest Profile**: Perfil de Descanso
