### ISSUE TITLE
Only Waterskins Available

### ISSUE THREAD

**Issue by Daegybyte** [roth-michael/FoundryVTT-RestRecovery#210]
When I do a long rest, I can only select from the waterskins to consume

**Expected behavior**
I should be able to add rations so that my character doesn't always get exhausted
Note: I have tried experimenting with different ration counts, like changing quantity or adding charges

**Screenshots**
<img width="679" alt="Screenshot 2024-05-19 at 9 40 23 PM" src="https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/55812910/4c33c5e2-ecd7-4d39-a959-67267cf418e6">

**Setup:**
 - Foundry Version: 11
 - System Version: DND5e 3.1.2
 - Rest Recovery Version: 1.6.6.1

**Comment by Daegybyte** [comment]
I figured out the issue. I use items exclusively from the DDB importer from Mr. Primate. I added rations from the basic SRD and your module worked great. I don't mind just using SRD rations. But I would love DDB integration. I will be reaching out to Mr. Primate as well  to see if he can change how rations are imported

**Comment by roth-michael** [comment]
Hmm, Rest Recovery SHOULD be automatically updating consumables. Let me check if it's something on this side of things. I can reproduce, with DDBI rations.

**Comment by Daegybyte** [comment]
Should I still reach out to Mr. Primate, or do you think this is a thing to be handled on your end? I am a big believer that it's possible to have too many cooks in the kitchen, so to speak.

**Comment by roth-michael** [comment]
Give me a little to check what the criteria is for consumable conversion. If it's something I think should be handled in DDBI, I'll reach out to Mr. Primate myself. Either way, will keep this issue open until resolved and keep you updated. Thanks for bringing it to my attention!
