### ISSUE TITLE
[BUG] When settings 2 units of water required per day, we can't input 2 water skins in the rest recovery dialog

### ISSUE THREAD

**Issue by edoreld** [roth-michael/FoundryVTT-RestRecovery#222]
**Describe the bug**
When settings 2 units of water required per day, and then taking a long rest, we can't fullfil the water requirements even if we have 2 water skins in the PC's inventory.

**To Reproduce**
1. Go to the module's settings -> Food & Water
2. Set "Units of Water required per day" to 2 and "enable food and water automation" to on
3. Create a PC
4. Give the user 2 waterskins
5. Take a long rest

Can't input my 2 water skins to fullfil the water requirements. If I put a 2 in the text box, it changes it to 1.

**Expected behavior**
Should be able to input 2 water skins

**Screenshots**
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/973854/3b1f5a40-4be3-45f4-a001-51e7f1ac3e81)

**Setup:**
 - Foundry Version: 11 Stable 315
 - System Version: D&D 3.1.2
 - Rest Recovery Version: 1.9.0
 - Browser & version using the Foundry client

**Active modules:**
[fvtt-midi-qol-troubleshooter.json](https://github.com/roth-michael/FoundryVTT-RestRecovery/files/15446814/fvtt-midi-qol-troubleshooter.json)

**Additional context**

**Comment by roth-michael** [comment]
Yep, can verify that that's happening. 
This isn't a Rest Recovery bug, so much as an function of the way the core system handles quantities of objects with charges - if they're not set to destroy on empty, then even if you fully use all charges, it'll just sit there at 0/1 (you can try this by using the waterskin manually - even if you have 3 of them, you can only use it equal to the number of charges).
There are two ways around this, both involve editing the waterskin item.
- You can check the "Destroy on Empty" box at the bottom of the "Consumable Usage" section of the item, in which case it will act exactly like food items, and will disappear from your inventory upon consumption, or
- You can increase the number of maximum charges per waterskin.

Personally I think the latter makes more sense; you own one waterskin, and can fill it with X units of water, as opposed to owning multiple waterskins and tossing them once empty. Will one of those options work for you?

**Comment by roth-michael** [comment]
Marking this as closed - feel free to get back to me if you've got any questions.
