### ISSUE TITLE
[BUG] Can't disable food & water tracking for a player

### ISSUE THREAD

**Issue by edoreld** [roth-michael/FoundryVTT-RestRecovery#223]
**Describe the bug**
When going to a player's Special Traits, I do not see the options to disable water & food tracking for that player.

**To Reproduce**
1. Create a PC
2. Go to PC's character sheet
3. Go to Details tab
4. Click on Special Traits button
5. Scroll down to Rest Recovery section

**Expected behavior**
Find the option to disable food & water tracking as per the wiki's instructions https://github.com/roth-michael/FoundryVTT-RestRecovery/wiki/Actor-Traits

**Screenshots**
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/973854/5ebfd165-8dca-45bd-a46a-5f4f57200c92)

**Setup:**
 - Foundry Version: 11 Stable 315
 - System Version: D&D 3.1.2
 - Rest Recovery Version: 1.9.0
 - Browser & version using the Foundry client

**Active modules:**
[fvtt-midi-qol-troubleshooter.json](https://github.com/roth-michael/FoundryVTT-RestRecovery/files/15446814/fvtt-midi-qol-troubleshooter.json)

**Additional context**

**Comment by roth-michael** [comment]
Just tested this: It looks like if you enable food & water automation, you need to restart the world before those settings update. I'll take a look and see if I can make that change happen automatically.
