### ISSUE TITLE
[BUG] Short rest setting "Hit Die roll multipier" also affects long rest

### ISSUE THREAD

**Issue by f4hy** [roth-michael/FoundryVTT-RestRecovery#231]
**Describe the bug**
The setting under Short Rest for "Hit Die roll multiplier" applies the multiplier to both short and long rests. Since the setting is under the short rest tab I would expect it to only affect short rests.

**To Reproduce**
1. Go to Settings for Short Rest. And on Long Rest set "Enable long rest hit dice rolls." 
2. Set the Hit Die roll multiplier setting to be "Quarter"
3. Prompt the users for a Long Rest
4. See the rolls only recover 0.25 the roll value.

**Expected behavior**
I would expect the setting to only affect rolls during short rests. Maybe the setting should be under General Settings rather than Short Rest tab. Or there should be a setting for this under both Short and Long rest tabs separately. 

**Screenshots**
<img width="218" alt="2024-06-01_15-40" src="https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/36440/6dafd3c5-af3d-4e74-8260-b9d0897984ff">

**Setup:**
 - Foundry Version: Version 11 build 315
 - System Version: DND5e 3.2
 - Rest Recovery Version: 1.10.4

**Active modules:**
 - Rest Recovery

**Additional context**
happy to contribute a fix.

**Comment by roth-michael** [comment]
Yup that's a valid point. It actually affects ALL hit die rolls, even those manually done outside of a resting context. I’ll move it to general settings in the next update.
