### ISSUE TITLE
NPC Rest Recovery with Tidy Sheet

### ISSUE THREAD

**Issue by DarkkingDraco** [roth-michael/FoundryVTT-RestRecovery#237]
Using Tidy Sheet, NPCs are allowed to take short or long rest. 

When Rest Recovery isn't installed, this function works. However, with Rest Recovery on, the pop up will go through the process but when it finishes nothing is updated or refreshed. 

Here is the error that appears in the console:
![RestRecovery_NPC_Error](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/121444989/0c490255-e80f-4d91-958a-d509668c21b2)

**Comment by roth-michael** [comment]
Hi, gonna look into this. Can you tell me - do your NPCs have hit dice to spend on a short rest or regain on a long rest? I just want to make sure I keep all the existing functionality of NPC rests (however much that is).

**Comment by roth-michael** [comment]
FYI in case you don't see the changelog, latest release should fix this. If you're on dnd 3.2, NPCs will get the full Rest Recovery treatment. If you're still on 3.1.x, they'll use the core rest, but at least won't throw any errors.

**Comment by DarkkingDraco** [comment]
Awesome! Thank you very much! To answer your question, I have been giving party companions sidekick classes which will give them hit dice. Other NPCs I just use this to refresh them after a fight they escape or otherwise.

**Comment by roth-michael** [comment]
Ah gotcha, that's new with Tasha's, right? Haven't gotten the chance to grab that and test it yet, so let me know if everything's working as expected!
