### ISSUE TITLE
[BUG] ENTER BUG NAME HERE

### ISSUE THREAD

**Issue by rinnocenti** [roth-michael/FoundryVTT-RestRecovery#239]
**Describe the bug**
When I click the button to call a long rest, I just get an error. and does not enter the rest panel

![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/3178127/138cc873-1fdf-4e30-929d-a7150cfed967)

**Comment by rinnocenti** [comment]
When there is a token without an actor it gives this error.

**Comment by roth-michael** [comment]
Gotcha, I should have a fix out for this pretty soon, thanks!
