### ISSUE TITLE
Song of Rest per Hit Dice spent

### ISSUE THREAD

**Issue by Sarge95k** [roth-michael/FoundryVTT-RestRecovery#242]
Song of rest is woefully underpowered and a common houserule is to let it apply to each hit dice used.
Solution would be for you to point the way for me to add this funcionality or to add it yourself (i am no JS writer but it seems that if SOR is called once on the 1st Hit Dice i see no reason it should be difficult to call multiple times)

Alternative way for me to get players to do this is target an ally and spam SOR feat on them for each HD they were told was spent.

If non implementation as a feature could you tell me where i should look and where to start with adjusting the module (never had a gander at the inside of one before)

Thanks
Smithy

Edit: Update: Looked through the Scripts and found all calls to song of rest however none had anything i could identify as a limiter to its uses. I suspect the relevant code I'm looking for is hidden above in further calls.

**Comment by roth-michael** [comment]
This should be something I can add in for the next release. In case you're curious, take a look at the `if` statement on line 695 of `rest-workflow.js` - and the relevant line a few lower at 709
