### ISSUE TITLE
When setting custom recoverery, it screws up the Simple Calender. 

### ISSUE THREAD

**Issue by Mezzarius** [roth-michael/FoundryVTT-RestRecovery#243]
**Describe the bug**
So if you go in and setup custom recovery, prevent players from using Rest, etc... on next reload the Simple Calender becomes bloated.

**To Reproduce**
1. Setup Custom Recovery
2. Reload

**Expected behavior**
I expected is to work, maybe it doesn't play nice with other mods?

**Screenshots**

**Setup:**
 - Foundry Version: 11.3.15
 - System Version: DND5e 3.2.0
 - Rest Recovery Version: 1.11.5
 - Browser & version Microsoft Edge

**Active modules:**
 - Rest Recovery
 - [insert more modules here]

**Additional context**

**Comment by roth-michael** [comment]
What exactly do you mean by "bloated"? Also, what Simple Calendar version, and could you share a screenshot?

**Comment by Mezzarius** [comment]
Well now it doesn't do it anymore and I don't know what I did differently, but hey Yay it works better, probably something I was doing wrong.

**Comment by roth-michael** [comment]
Hooray!
