### ISSUE TITLE
[BUG] Feature Name change (Song of Rest) not working

### ISSUE THREAD

**Issue by cwlithgow** [roth-michael/FoundryVTT-RestRecovery#255]
Renaming the Song of Rest to "Hands of a Healer" doesn't seem to work - unless I have the format wrong?
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/85030999/89fd2808-c210-4981-9b46-ae300587c122)

results in this:

![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/85030999/994f60c8-ba5e-441f-aa94-55cc2a97b266)

**Setup:**
 - Foundry Version: [12.328]
 - System Version: [e.g. DND5e 3.2.1]
 - Rest Recovery Version: [e.g. 1.14.0]
 - Browser & version [e.g. Google Chrome 126.0.6478.127]

**Active modules:**
 - Rest Recovery - all others disable

**Comment by roth-michael** [comment]
Just to be clear, you changed the name in the settings and also the name of the item? And if so, it's picking it up properly but just displaying the wrong name in the chat message? If so I should be able to put out a fix for the message soon, thanks for noticing.

**Comment by cwlithgow** [comment]
Thats exactly right. However I did forget to mention that I am running a custom character sheet mod as well:
https://github.com/ZWinther/lotr5e-module
I have it locked because characters that are created with it won't open if that mod is disabled so i forgot about it. Perhaps thats tied in to the issue.
Thanks for your consideration!

**Comment by roth-michael** [comment]
Gotcha. Nope that's purely a Rest Recovery issue - will fix in the next release!
