### ISSUE TITLE
[BUG] Bard's Song of Healing not applying to logged in players.

### ISSUE THREAD

**Issue by cwlithgow** [roth-michael/FoundryVTT-RestRecovery#256]
Logged in players do not recieve the Bards Song of Healing bonus dice unless they are the Bard themselves. Unconnected players where the GM "finishes the rest for them" it applies OK.

Foundry Version: [12.328]
System Version: [e.g. DND5e 3.2.1]
Rest Recovery Version: [e.g. 1.14.0]
Browser & version [e.g. Google Chrome 126.0.6478.127]

**Active modules:**
 - Rest Recovery only (including disabling the LOTR sheet I mentioned in the last bug report)
 

I do not have this checked:
![image](https://github.com/roth-michael/FoundryVTT-RestRecovery/assets/85030999/11eb92ce-1026-4891-a1de-96b6b2f841f9)
(although I tried with and without it checked..this part seems to work as intended.)

I promise I'm done bug hunting for now. The Song of Healing effect is the prime reason I sought out this module - although I'm sure I'll use more of it as I dig in.
Thanks again.

**Comment by cwlithgow** [comment]
Happy to jump on a discord chat if that would help you at all. I'm EST

**Comment by roth-michael** [comment]
EST as well - will give this some testing and if I have trouble replicating will let you know. To confirm, are you starting a test through the Rest Prompt?

**Comment by cwlithgow** [comment]
Thanks!
With the rest prompt below the character list, yes. I have tried it with the rest buttons on the characters sheets as well - all seemed to act the same way

**Comment by roth-michael** [comment]
And also, the bard is one of the selected players in the rest?

**Comment by cwlithgow** [comment]
> And also, the bard is one of the selected players in the rest?

Correct!
