### ISSUE TITLE
[BUG] [Request] No Players/Characters Clicking +

### ISSUE THREAD

**Issue by Busted478** [roth-michael/FoundryVTT-RestRecovery#258]
I'm not sure if this is a bug, an improvement idea or maybe it's working as intended. If nothing else, maybe this will help someone else.

I have a game world I've been testing for a new game. I'd click the rest button in the players list in the lower left corner and then try to click the + next to Player characters to prompt rest for, but nothing would come up. Since the game hasn't officially started, my world only contains a couple of pre-made characters which is where my problem was. I'll have a player sign in and claim one of the pre-made characters. The pre-made characters are configured so that all players have owner and each individual player has default. Once, I gave an individual player Owner rights, I see them when I click the +.

Is it possible to pull the player/character from the players list?
![image](https://github.com/user-attachments/assets/074e2ca2-2430-4a07-8acf-23f2eeb67bae)

**Setup:**
 - Foundry Version: [11.315]
 - System Version: [DND5e 3.2.1]
 - Rest Recovery Version: [1.14.1]
 - Browser & version [Google Chrome 126.0.6478.182]

**Active modules:**
 - Rest Recovery
I have 55 active modules. I'll post them all if needed.

**Comment by roth-michael** [comment]
Not 100% sure I understand the potential bug. To confirm, an actor will only show up in the list if they have a player owner assigned. After that, all of them should be visible in the dropdown, with priority given to those actors which have tokens on the active scene (and whichever group of actors chosen for a rest should be remembered between rests).

**Comment by Busted478** [comment]
I've pulled in 5 pre-made characters so a player can assign one to themselves and start playing.
![image](https://github.com/user-attachments/assets/6286f129-c978-4206-9656-e3b2109b834e)

Each one has the same ownership configuration with "All Players" having "Owner" and each individual player having "Default" ownership.
![image](https://github.com/user-attachments/assets/a4f50087-4082-4c9f-9939-2fca0b601df5)

When a player logs in, they're able to assign one of the characters to themselves if they're not already assigned one.
![image](https://github.com/user-attachments/assets/7a98cee6-e9f5-4614-b96d-c6b1cfdd2691)

Once a player has assigned themselves to a character, the player list shows Player [Character].
![image](https://github.com/user-attachments/assets/24cece2b-7dd1-4ea1-a6c2-d5a8702b29d6)

However, clicking the + doesn't let me select a character. The player and character are both active in the scene.
![image](https://github.com/user-attachments/assets/d99f26d8-5c5b-46d2-a116-0c3623cdc62b)

If I change the character's owner to "Owner" of a specific Player, it will work.
![image](https://github.com/user-attachments/assets/4612ae6a-0a29-42eb-8f51-c6fe3b77e43d)
![image](https://github.com/user-attachments/assets/ffd2534e-ac03-4771-9552-a76d9c028a73)

Sorry for all the pictures. It was easier to show what's I'm seeing.

I'm not sure if it is a bug or not. If not, maybe an improvement idea. If neither, I know the workaround now.

**Comment by roth-michael** [comment]
Ahhh I see. I’ll look into this. I didn't consider the situation where all players are owners by default.
