### ISSUE TITLE
[BUG] "Access to external food and water" is broken for me

### ISSUE THREAD

**Issue by TrofimSelbs** [roth-michael/FoundryVTT-RestRecovery#259]
**Describe the bug**
I have allowed my players to choose "has access to external food and water" to mark the fact that they have hunted and eaten something. So they have access to the external food. However when they click on the option - they are no longer allowed to finish the long rest coz "they haven't eaten enough yet"

**To Reproduce**
1. Allow "External food and water sources"
2. Leave them to have no cost
3. Go to a character sheet and start a long rest
4. Go to the "Food and water" part of it
5. See video below

**Expected behavior**
It will allow me to select that I have external food, and external water, and allow me to finish a long rest.

**Screenshots**
https://github.com/user-attachments/assets/ad761359-8c56-411b-8b88-c1b3efa95d69

**Setup:**
 - Foundry Version: [v11 315]
 - System Version: [DND5e 3.1.2]
 - Rest Recovery Version: [e.g. 1.6.9]
 - Browser & version [Google Chrome 127.0.6533.73]

**Comment by TrofimSelbs** [comment]
![image](https://github.com/user-attachments/assets/d69be591-8a2a-41f0-a7bb-dd902a87b87e)
forgot to include list of other modules active

**Comment by roth-michael** [comment]
Could you send along a pic of your Food & Water settings as well? I'm unable to reproduce this so maybe matching your settings will give me more luck.

**Comment by TrofimSelbs** [comment]
Here are my settings


![image](https://github.com/user-attachments/assets/819c671a-8b38-4e9a-b8b4-97c648c2bf39)
![image](https://github.com/user-attachments/assets/3d6266fe-a447-4393-8878-62d300012609)
![image](https://github.com/user-attachments/assets/198d3a9f-9b77-4716-86be-9e2f2ca6b9ed)
![image](https://github.com/user-attachments/assets/3c85221e-66e9-435d-8542-dca3038ec9bb)


[Custom.json](https://github.com/user-attachments/files/16373273/Custom.json)

**Comment by TrofimSelbs** [comment]
I am on 1.14.1 version of Rest Recovery

**Comment by roth-michael** [comment]
Hm. I've spun up a test world with the same versions & settings as you and cannot reproduce. Could you try
1. Enabling food/water cost, saving, then disabling again and saving?
2. Trying in a fresh world?

**Comment by TrofimSelbs** [comment]
huh yea. the first step didn't fix it, but the second one does. I will search what modules can possible interfere

**Comment by TrofimSelbs** [comment]
ahh I found the culprit. that was the module World Currency 5e. I disabled all of the modules (see screenshot above), but for some reason it remained active. I would guess that this is because it modified something in one of these libraries:
- dlopen
- lib - Color Settings
- libWrapper
- routinglib
- socketlib
- Rest Recovery for 5E

**Comment by roth-michael** [comment]
Interesting - I'll see if I can look into why World Currency 5e would break it and leave this ticket open until I either determine a fix or determine that I won't be finding a fix. Thanks for bringing this to my attention!

**Comment by TrofimSelbs** [comment]
thank you for giving it a shot! If I were to guess why it would be breaking -> my custom currency is not in Latin characters, but in Cyrylics. Maybe that is why? Anyway, thank you for your time!

**Comment by TrofimSelbs** [comment]
My theory just got a few more points towards it's correctness. 

1. I have disabled World Currency
2. It started to work (and currency is in English)
3. I used "Custom dnd 5e" module to modify currency once again (making it in cyrilics)
4. It stopped working

It is likely that not the "World Currency" module itself is the problem

**Comment by Nolat** [comment]
I have the same bug, but without World Currency or System Customizer, simply by having Foundry in French.

I've investigated a bit and the problem seems to come from those lines: https://github.com/roth-michael/FoundryVTT-RestRecovery/blob/601d88dcf353ff3c8d98d0b1dd328500b6bd7963/scripts/formapplications/rest-steps/FoodWater.svelte#L308-L309

Here currencyData is localized (e.g. po instead of gp in french) but actor.system.currency is not.
![image](https://github.com/user-attachments/assets/1297cf26-17dc-42fd-be74-e47e794e332c)

So actorWealth is always in NaN, no matter what.

**Comment by roth-michael** [comment]
Ahh great, thank you. That should be fixable. Will give it a shot.
