### ISSUE TITLE
[BUG] Item Piles Button

### ISSUE THREAD

**Issue by Kharmans** [roth-michael/FoundryVTT-RestRecovery#268]
In a bug report for Item Piles, the author says that Rest Recovery is changing the name of the Trade button from Item Piles, don't respecting the localization of the module.

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/foundry-ui-overrides.js#L51-L63

Can it be corrected?

**Comment by roth-michael** [comment]
Yup, plan to put out a fix tomorrow. Item Piles author let me know about it. No extra work for you though, as I’ll just use the new Item Piles localization for it.
