### ISSUE TITLE
Not able to click the actual button to end the long rest

### ISSUE THREAD

**Issue by Weskernation** [roth-michael/FoundryVTT-RestRecovery#278]
**Describe the bug**
Able to start the long rest dialog. Players are able to select the items they want to eat/drink. But the moment the actual button needs to be clicked to continue/end the long rest. the button is blocked

**To Reproduce**
![image](https://github.com/user-attachments/assets/8bf2d69a-ccf4-40fc-ad15-d9a4c22174cf)

![image](https://github.com/user-attachments/assets/f26096c7-ea79-4bc5-a23b-85ddb0572c7d)
<img width="333" alt="{F6C9FCA0-E329-4B26-8058-AD0DA25122A3}" src="https://github.com/user-attachments/assets/078b5e8f-e758-4452-8080-6f9431bd1242">
<img width="337" alt="{B5DD4C8B-8033-4A00-BAF7-DDFE34BD8CA8}" src="https://github.com/user-attachments/assets/97b9b026-2398-42b9-b18e-774d47d267bd">
3. See error -> not able to click on the "Finish Long Rest" button

**Setup:**
 - Foundry Version: [12.331]
 - System Version: [DND5e 3.3.1]
 - Rest Recovery Version: AFTER [1.14.1] (1.14.1 is the last version everything works without any issues)
 - Browser & version [e.g. Google Chrome latest]

**Active modules:**
 - Rest Recovery

**Additional context**
version 1.14.1 works fine, no issues
version 1.15.0 and after

**Comment by roth-michael** [comment]
Any bugs showing up in the console (f12 on most devices) when you try to click the Finish Long Rest button?

**Comment by roth-michael** [comment]
Solution found, for anyone with the same issue: World Currency 5e was the issue. EP was being hidden, but had no conversion rate set, leading to an error. To fix:
1. Unhide EP in World Currency 5e.
2. Re-open World Currency 5e settings (maybe a refresh is necessary), enter some value for conversion rate.
3. Re-hide EP in World Currency 5e.
