### ISSUE TITLE
Custom Wizard Class - Recovery Not Working

### ISSUE THREAD

**Issue by XXDarrienX** [roth-michael/FoundryVTT-RestRecovery#284]
**Describe the bug**
When doing a short rest, it says 0 spell slots available for recovery for my Wizard overwrite

**To Reproduce**
1. Change Wizard class to a different class
2. Have all spell slots open
3. Short Rest
4. No spell slots to recover

**Expected behavior**
Expected to recover spell slots

**Screenshots**
![image](https://github.com/user-attachments/assets/eb5918c3-1e3b-440d-a6bc-dba39998604d)
![image](https://github.com/user-attachments/assets/f3380cfb-570d-47fa-82db-61c4d694c087)
![image](https://github.com/user-attachments/assets/c1a93e6c-1a0a-409e-ab2a-26f4976295cb)

**Setup:**
 - Foundry Version: 12.331
 - System Version: DND5E 3.3.1
 - Rest Recovery Version: [e.g. 1.17.0
 - Browser & version Chrome 130.0.6723.71

**Active modules:**
Active Modules:
----------
Abomination Vaults maps remake v;
About Time v;
Active Auras v;
Active Token Effects v;
Advantage Reminder for dnd5e v;
Agents of Edgewatch maps remake v;
Alternative Token Cover v;
Always HP v;
Angela Maps - Free Map Pack v;
Animated Spell Effects (Jack Kerouac) v;
Anonymous v;
Argon - Combat HUD (CORE) v;
Argon - Combat HUD (DND5E) v;
Autocomplete Inline Properties v;
Automated Animations v;
Automated Evocations - Companion Manager v;
Baileywiki Mass Edit v;
Beaver's Crafting Module v;
Beaver's System Adaptation dnd5e v;
Beaver's System Interface v;
Better Roofs v;
BLFX Assets & Animation Editor Free v;
Boss Loot Interactive Magic Items, Free Pack v;
Bugbear's Scripts v;
Build-a-Bonus v;
Caeora's Maps, Tokens, and Assets v;
Carousel Combat Tracker v;
Cauldron of Plentiful Resources v;
Chat Commander v;
Combat Booster: Turn Marker, Recent Actions and more v;
ConversationHUD v;
Cosmic Dice v;
Cozy Maps - Free v;
Cursor Hider v;
Damage Log v;
D&D5e Animations v;
D&D5e Character Monitor v;
DFreds Chat Pins v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice Tray v;
Dig Down - Advanced Search v;
DnD5e Drag Ruler Integration v;
DND5E Scriplets - 5E QOL bits and pieces v;
Domille's Wondrous Works - Battlemap Collection v;
Domille's Wondrous Works Free Phased Battle Maps v;
Domille's wondrous works - Scene Phaser (Free version) v;
Door Sounds v;
Drag Ruler v;
Drag Upload (Get Over Here!) v;
Drehatlas' Maps v;
Dynamic effects using Active Effects (DAE) v;
Easy Exports v;
Easy Regions v;
Effect Macro v;
Elven Tower Free Maps v;
Extinction Curse maps remake v;
Fall of Plaguestone maps remake v;
Filepicker Improvements v;
Force Client Settings v;
Forgotten Adventures Battlemaps v;
Forien's Copy Environment v;
Foundry Community Macros v;
Foundry Community Tables v;
Frag Maps - Modern, Cyberpunk and Sci-Fi Maps v;
FXMaster v;
Gambit's Premades v;
GM Notes v;
GM Screen v;
GM Vision v;
Grid Scaler v;
Health Estimate v;
HoloGrounds Free Maps v;
Hyperdrive Fleet - Asteria - Luxury Space Yacht v;
Hyperlanes v;
Icon Picker v;
Illandril's Inventory Sorter (5e) v;
Image Previewer v;
Ironfang Invasion Maps Remake v;
Item Piles v;
Jack Kerouac's Animated Spell Effects: Cartoon v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
Kobold DM Kingmaker Maps (Remakes) v;
Lancer Weapon FX v;
Levels v;
lib - Color Settings v;
Library: DF Module Buttons v;
Library - Find the Path v;
Library: Scene Packer v;
libWrapper v;
Limits
                            3 limitRange Region Behaviors v;
Lock & Key v;
Macro Grid v;
Magic Items v;
Malevolence Reimagined Maps by Narchy v;
Mark's Mark of the Mantis Maps v;
Math.js v;
Merge Walls v;
Midi Item Showcase - Community v;
Midi QOL v;
MikWewa Free Maps v;
Milby's Maps Free v;
Miska's | Alien Wastelands v;
Miska's | Colony Outpost v;
Miska's | Docking Bay 21 (MM311) v;
Miska's | HyperCorp Lobby (MM317) v;
Miska's | Jungle Bio-Lab (MM314) v;
Miska's | Jungle Valley Zone (MM312) v;
Miska's Maps #315 - HyperCorp Boardroom v;
Miska's Maps - Battlemaps - Starter Pack v;
Miska's | Parking Hall (MM316) v;
Miska's | Pilgrim-Class Hauler (MM309) v;
Miska's Sci-fi & Fantasy Scene Collection Vol 01 v;
Miska's Sci-fi & Fantasy Scene Collection Vol 02 v;
Miska's Sci-fi & Fantasy Scene Collection Vol 03 v;
Miska's Sci-fi & Fantasy Scene Collection Vol 04 v;
Miska's Sci-fi & Fantasy Scene Collection Vol 05 v;
Miska's Sci-Fi Scenes 02 v;
Miska's Sci-Fi Scenes 03 v;
Miska's Sci-Fi Scenes 04 v;
Miska's Sci-Fi Scenes 05 - Proteus Outpost v;
Miska's | Secret Lairs v;
Miska's | Space Bodega (MM310) v;
Miska's | Space Colony 01 v;
Miska's | Spaceship Deckplans 01 v;
Miska's | Xenomorph Nest (MM308) v;
Mob Attack Tool v;
Monk's Active Tile Triggers v;
Monk's Bloodsplats v;
Monk's Combat Details v;
Monk's Enhanced Journal v;
Monk's Hotbar Expansion v;
Monk's Little Details v;
Monk's Scene Navigation v;
Monk's Shops v;
Monk's Sound Enhancements v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Moonlight Maps v;
Multiface Tiles v;
Multilevel Tokens, by Beneos v;
Multiple Document Selection v;
Nachtrose's Sci-Fi ( and modern ) Animated Pack v;
Night of the Gray Death Maps Remake v;
Note Licker v;
Not Your Turn! v;
Party Inventory v;
Party Resources v;
Patrol v;
PF2e QftFF Maps v;
Pin Cushion v;
Pings v;
Polyglot v;
Portal v;
Pull Players to Scene v;
Quick Insert - Search Widget v;
Region Active Effects
                            5 activeEffect Region Behaviors v;
Region Attacher v;
Region Enchantment v;
Rest Recovery for 5E v;
Rideable v;
Rise of the Runelords Maps by Narchy v;
Roll Table from Sidebar and Journal v;
routinglib v;
Sequencer v;
Settings Extender v;
Simbul's Athenaeum v;
Simbul's Creature Aide v;
Simbul's Template Scaling v;
Simple Calendar v;
SmallTime v;
Smart Target v;
socketlib v;
SocketSettings by Blitz v;
SoundFx Library v;
Speak As…… v;
Status Halo v;
Stealthy v;
Stroud's DnD Helpers v;
TacticalMap Battlemaps v;
Tagger v;
Tasteful Tooltips v;
Terrain Mapper v;
The Forge v;
The Forge: More Awesomeness v;
The Reclusive Cartographer | Free Foundry Content v;
TheRipper93's Module Hub v;
Tidy 5e Sheets v;
Tidy UI - Game Settings v;
Times Up v;
Token Action HUD Core v;
Token Action HUD D&D 5e v;
Token Attacher v;
Tokenizer v;
Token Light Condition v;
Token Magic FX v;
Token Says v;
Token Variant Art v;
Torch v;
Troubles in Otari maps remake v;
Universal Animations v;
Universal Battlemap Importer v;
Vision 5e v;
Visual Active Effects v;
Walled Templates v;
Wall Height v;
WFRP4E - Fan-made maps for Death on the Reik v;
WFRP4E - Fan-made maps for Ennemy in Shadows v;
WFRP4E - Fan-made maps for Power Behind The Throne v;
WFRP4E - Fan-made maps for Ubersreik and its area v;

Inactive Modules:
----------
Advanced Macros v;
Automated Conditions 5e v;
Baileywiki Free Maps Pack v;
Better Roll Tables v;
Chibbin Grove Free Compendium v;
Custom Character Sheet Sections v;
Custom D&D 5e v;
Czepeku Sci-Fi - Arctic Institute v;
Czepeku Sci-Fi - Magnus Starship Part 1 v;
Darkraven Games Free Fantasy and Sci-Fi Soundscapes v;
DDB-Importer: A D&D Beyond Integrator v;
DF Chat Enhancements v;
DF Curvy Walls v;
DFreds Droppables v;
Elevation Ruler v;
Find the Culprit v;
Hyperdrive Fleet - Ouroboros v;
Hyperdrive Fleet - Ouroboros Part 2 v;
Hyperdrive Fleet - Ouroboros Part 3 v;
Kanka-Foundry v;
👻 KASPER | Karma Assessment and Player Evaluation Resource v;
Lib: Document Sheet Registrar v;
Map Doctor: Free Bundle v;
Mark Drummond J - Free Pack v;
Maxwell's Manual of Malicious Maladies v;
Miska's Maps #380 - Aurora-Class Shuttle Deckplan v;
Miska's Maps #450 - Megacorp Offices v;
Monk's Enhanced Journal Objectives styles v;
Monument Studios Sampler v;
RuinWorks Free Content v;
Rush - Mob Movement v;
Simbul's Cover Calculator v;
Spellarena Battlemap Collection v;
Status Icon Counters v;
Super's Homebrew Compendium v;
Tabbed Chatlog v;
The Heracles v;
WTF: What the Flag? v;

**Additional context**
So I tried changing the Genius class identifier to wizard instead on the character but it made it as if magic recovery was not there. I still left it as Brilliant Recovery though.

**Comment by roth-michael** [comment]
Solution to this:
The "Other Formula" field of the arcane recovery (brilliant recovery, in this case) item needed to be modified to be `ceil(@classes.genius.levels/2)` rather than `ceil(@classes.wizard.levels/2)` (the setting for an alternate class name is _only_ for an alternate class _name_, not the identifier, so this info couldn't be known ahead of time).
