### ISSUE TITLE
[BUG] 2.1.1 breaks Token Action HUD in DnD5e 4.0.4

### ISSUE THREAD

**Issue by nschoenwald** [roth-michael/FoundryVTT-RestRecovery#285]
**Describe the bug**
After this module updated, Token Action HUD does not work anymore. When selecting a token, the HUD does not show. There was never a problem with both modules active before and after rolling Rest Recovery back to 2.1.0, it works again.

Foundry 12.331
DnD5e 4.0.4
Token Action HUD Core 1.5.7
Token Action HUD D&D 5E 1.6.6

**Comment by BadNerdCreating** [comment]
the same thing happened to me. I have the same settings in terms of Foundry and DnD5e and Token Action HUD. Enabling the module erased the HUD. There was also no indicator of players food or water levels.

**Comment by roth-michael** [comment]
Hi - could you confirm whether this behavior is still happening with the latest releases of Token Action HUD Core & D&D?  (2.0.6 and 2.0.2, respectively).

**Comment by nschoenwald** [comment]
For me, it does not occur anymore after updating everything just now and giving it a quick look.

**Comment by roth-michael** [comment]
Great. Will mark this closed then, can be reopened if the issue persists for anyone else.

**Comment by nschoenwald** [comment]
Actually still occurs for me. I forgot I disabled Rest Recovery because of the other issue with Lay on Hands.
Current versions of all modules, dnd5e system and Foundry V12.

<img width="398" alt="image" src="https://github.com/user-attachments/assets/3a60ed7c-d854-41b4-a399-3aa24c744d8d">

**Comment by roth-michael** [comment]
Ahh hmm. It seems to be working for me. I'll investigate further though

**Comment by roth-michael** [comment]
Got it. It's an issue when One D&D Exhaustion is enabled. Should be able to figure it out.
