### ISSUE TITLE
[Request] display a characters food or water needs on the actor sheet

### ISSUE THREAD

**Issue by BadNerdCreating** [roth-michael/FoundryVTT-RestRecovery#289]
Unless I missed something there doesn't seem to be any display for the food and water needs of the actors. I would love to use this mod but I can't because it doesn't seem fair to require my players to just memorize how much they have ate or drank for the day. Or they'll just immediately do it after every long rest and then it just seems like an unnecessary step.

**Comment by BadNerdCreating** [comment]
so I played with it some more. is the food and water requirement just for long and short rests? so eating or drinking outside of that does nothing?

**Comment by roth-michael** [comment]
![image](https://github.com/user-attachments/assets/512775c5-d1b0-42f4-8af4-28b20214a633)
Assuming 4.x, you'd want to ensure the "Food Type" field (which is added by Rest Recovery) is nonempty, as above. (Though now that I'm testing I'm actually seeing a different error in the chat card)

**Comment by BadNerdCreating** [comment]
I see now why there's no display for food and water needs. It could still be implemented but it would be much more complicated. For example I set my food and water need to 3. So you could implement it so that a player gets exhaustion from not eating during the long rest but can remove the exhaustion by eating 3 units through-out the day. for example, when they get to a tavern or something. 
but that's not really how exhaustion works in DnD and would be much more complicated to put into the module. (i imagine)

**Comment by roth-michael** [comment]
That's right. A "real-time" sort of food/water system would be a different module. At most I could potentially add a "2 units of food still required" sort of thing to character sheets, but I think that might be unnecessary bloat since when food is eaten outside of a rest it tells you how much more is needed
