### ISSUE TITLE
[BUG] quanity of food & water with charges not recognized

### ISSUE THREAD

**Issue by BadNerdCreating** [roth-michael/FoundryVTT-RestRecovery#292]
The module doesn't recognize when you have multiples of a food or water with charges. Waterskins have 4 charges. I also made a new food item and gave it 4 charges. Then I gave the actor multiples of both. So 4 waterskins and 4 food items. The module doesn't recognize that there are multiples.

ex. If a player has 4 waterskins in their inventory and it shows 1 charge the module only recognizes there being 1 water available. Not the 12 charges from the 3 other waterskins. This happens with both items marked food and water. 

This can be fixed in foundry by editing the item under details and usage. Check destroy on empty and then then module will show 16 units of water for 4 waterskins instead of just 4. It would just be nice if the module handled this itself. 

It's also possible to make an effect that tells the item to not stack in the inventory but that had unpredictable results. For a different custom weapon I made an effect with :
Attribute Key: Quantity 
Change Mode: Override 
Effect Value: 1. 
This worked for the custom weapon but didn't give consistent results for the water or food.

**Comment by roth-michael** [comment]
See my comment on #222 
It's a fundamental property of the way the system treats potentially stackable items. If something has limited uses, it should not be stackable unless it's "destroy on empty."

The way the 2024 PHB handled this was by making waterskins into containers, and creating a "Water (Pint)" item to put in them.

**Comment by BadNerdCreating** [comment]
okay, that's unfortunate it can't be changed but I appreciate the explanation. My bad on missing the other post. Thanks again!
